### ISSUE TITLE
Allow infiltrating foreign tasks

### ISSUE THREAD

**Issue by dpsanders** [JuliaDebug/Infiltrator.jl#58] opened 2022-01-16 19:28 UTC
The PR #57  broke my workflow, since apparently I *need* to infiltrate foreign tasks! 

Could there be some kind of `foreign=true` keyword argument?

**Comment by pfitzseb** [comment] 2022-01-16 20:17
You can set `Infiltrator.CHECK_TASK[] = false`, which should allow for your previous workflow.

I think I can come up with a slightly better fix for this though. Can you share your usecase (I'm assuming you just have a `@sync @async foo()` somewhere, which I apparently didn't think about on Friday).

**Comment by andyDoucette** [comment] 2022-01-21 10:07
Also broke mine.  Here's an example, taken from the readme:

test.jl
```
using Infiltrator

function f(x)
    out = []
    for i in x
        push!(out, 2i)
        @infiltrate
    end
    out
end

f([1, 2, 3])
```
in Julia 1.6.5.:
```
julia> include("test.jl")
Cannot infiltrate foreign tasks. Disabling infiltration point at f(x::Vector{Int64}) at test.jl:30.
3-element Vector{Any}:
 2
 4
 6

```

**Comment by pfitzseb** [comment] 2022-01-21 10:36
That works fine for me. In what environment are you running that code? Juno? VS Code?

**Comment by andyDoucette** [comment] 2022-01-22 00:32
It's a docker container.

Dockerfile
```
FROM julia:1.6.5-bullseye

#Make sure that we don't get interactive prompts during installs:
ENV DEBIAN_FRONTEND=noninteractive

#Install system dependencies:
RUN apt-get update && apt-get install -y sudo nano gosu htop && \
    rm -rf /var/lib/apt/lists/*

#Allow any sudo group users to do sudo without a password.
RUN echo '%sudo   ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers

#This is hard-coded in many places, so please don't change this unless you change it everywhere:
WORKDIR /app/src

#Allow users of the sudo group to use sudo without a password (allows our "user" user to sudo.)
RUN echo '%sudo   ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

#Make sure the julia binary file is in the path:
RUN ln -s /usr/local/julia/bin/julia /usr/local/bin/

#Set the number of threads we will use
ENV JULIA_NUM_THREADS=60

#Start Instantiate our Julia:
COPY ./*.toml ./
RUN julia --project=./ -e 'using Pkg; Pkg.instantiate()'

COPY . ./

#Use a path that includes /app/src/cli:
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/src/cli
```

To reproduce:  with Dockerfile, Project.toml, and test.jl in the same directory, run:

```
docker build -t inf . && docker run -it inf /usr/local/bin/julia --project=.

```

Then enter:
```
julia> include("./test.jl")
```

**Comment by andyDoucette** [comment] 2022-01-22 00:33
If it matters, I'm running rootless docker v20.10.12 build e91ed57, which I installed with this procedure:

```
#Removing old docker:
sudo apt-get remove -y docker docker.io containerd runc

#Installing docker-ce:
sudo apt-get update
sudo apt-get install -y  uidmap ca-certificates     curl     gnupg     lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo   "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

#Setting up rootless:
sudo apt-get install -y docker-ce-rootless-extras
sudo systemctl stop --now docker.service docker.socket
sudo systemctl disable --now docker.service docker.socket
dockerd-rootless-setuptool.sh install --force

#The rest needs to be run by each user who wants to use this:
sudo loginctl enable-linger $(whoami)

echo '

#Allows us to use docker rootless mode for this user:
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock' >> ~/.bashrc

source ~/.bashrc

#Test:
docker run -it ubuntu echo 'hello world'
```

**Comment by andyDoucette** [comment] 2022-01-22 00:34
[andromodon@potens tmp]$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

**Comment by pfitzseb** [comment] 2022-01-22 14:19
Can you try whether https://github.com/JuliaDebug/Infiltrator.jl/pull/62 fixes the issue?

**Comment by andyDoucette** [comment] 2022-01-22 17:56
I made the docker container so you can reproduce it.  Can you try it on
your side first?  That's much more efficient than me being in the loop.

**Comment by pfitzseb** [comment] 2022-01-27 13:31
Foreign task detection should be more correct with the latest release, so do give that a go.

**Comment by NHDaly** [comment] 2022-04-18 20:10
I'm just catching up here, but with your latest fixes, do we still need to set `Infiltrator.CHECK_TASK[] = false`?

If Infiltrator supports foreign tasks now, why do we need the foreign task check at all? Thanks! :)

**Comment by pfitzseb** [comment] 2022-04-18 22:15
Foreign tasks aren't really supported, no. You can still set `CHECK_TASK[] = false` if you run into this issue and know what you're doing.

The check is indeed more correct nowadays, but the premise isn't quite correct -- it really should check that the REPL task is busy, because in that case we can safely switch to a different REPL mode (re-opening this so I don't forget).

**Comment by pfitzseb** [comment] 2022-06-15 17:58
Fixed by https://github.com/JuliaDebug/Infiltrator.jl/commit/1511e49adc444730e3aac30d848c5198836dcace.

**Closed by pfitzseb** 2022-06-15 17:58 UTC
Labels: enhancement
